// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdh27vowtNaTg-sS3W9vQPcmawH_8H1m4',
    appId: '1:175333885943:web:47499fb85803bc83a090f2',
    messagingSenderId: '175333885943',
    projectId: 'schooly-cfb30',
    authDomain: 'schooly-cfb30.firebaseapp.com',
    storageBucket: 'schooly-cfb30.firebasestorage.app',
    measurementId: 'G-QFQ37PFSKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzgYVE0_N8EWGz1wvr9zl8IMduAewY3s',
    appId: '1:175333885943:android:9a5aa899e7b0e15fa090f2',
    messagingSenderId: '175333885943',
    projectId: 'schooly-cfb30',
    storageBucket: 'schooly-cfb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8-SLWwzdWSx0NOLasqs3vRIDBwyTgaYI',
    appId: '1:175333885943:ios:b4651bb435d8ac5da090f2',
    messagingSenderId: '175333885943',
    projectId: 'schooly-cfb30',
    storageBucket: 'schooly-cfb30.firebasestorage.app',
    iosBundleId: 'com.example.schooly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8-SLWwzdWSx0NOLasqs3vRIDBwyTgaYI',
    appId: '1:175333885943:ios:b4651bb435d8ac5da090f2',
    messagingSenderId: '175333885943',
    projectId: 'schooly-cfb30',
    storageBucket: 'schooly-cfb30.firebasestorage.app',
    iosBundleId: 'com.example.schooly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdh27vowtNaTg-sS3W9vQPcmawH_8H1m4',
    appId: '1:175333885943:web:20ac914d329b0c0ba090f2',
    messagingSenderId: '175333885943',
    projectId: 'schooly-cfb30',
    authDomain: 'schooly-cfb30.firebaseapp.com',
    storageBucket: 'schooly-cfb30.firebasestorage.app',
    measurementId: 'G-0104B6T2E6',
  );
}
